'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { BookOpenCheck, Search, Trash2 } from 'lucide-react';

type Enrollment={entitlementId:string;userId:string;email:string;fullName:string;courseId:string;courseTitle:string;courseSlug:string;grantedAt:string};
export function AdminEnrollments(){
  const[items,setItems]=useState<Enrollment[]>([]);const[query,setQuery]=useState('');const[busy,setBusy]=useState('');const[message,setMessage]=useState('');
  const load=useCallback(async()=>{const response=await fetch('/api/admin/enrollments',{cache:'no-store'});if(response.ok)setItems(((await response.json())as{enrollments:Enrollment[]}).enrollments)},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
  const shown=useMemo(()=>{const needle=query.trim().toLowerCase();return needle?items.filter(item=>`${item.fullName} ${item.email} ${item.courseTitle}`.toLowerCase().includes(needle)):items},[items,query]);
  async function remove(item:Enrollment){if(!window.confirm(`Remove ${item.courseTitle} from ${item.email}?`))return;setBusy(item.entitlementId);setMessage('');const response=await fetch('/api/admin/enrollments',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({userId:item.userId,courseId:item.courseId})});if(response.ok){setItems(current=>current.filter(entry=>entry.entitlementId!==item.entitlementId));setMessage('Course access removed.')}else setMessage('Could not remove course access.');setBusy('')}
  return <section className="mt-10 rounded-xl border bg-white p-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="font-heading text-2xl font-bold">Purchased course access</h2><p className="mt-1 text-sm text-[#5d696c]">Find a learner and remove access to a specific course.</p></div><span className="rounded-full bg-[#e8f3ff] px-3 py-1.5 text-sm font-semibold text-[#0757B2]">{items.length} active</span></div><label className="mt-5 flex max-w-xl items-center gap-3 rounded-lg border px-4"><Search size={17}/><input className="h-11 flex-1 outline-none" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search by learner, email or course"/></label>{message&&<p className="mt-3 text-sm font-semibold text-[#087861]">{message}</p>}<div className="mt-5 grid gap-3">{shown.map(item=><article key={item.entitlementId} className="flex flex-col gap-4 rounded-lg border p-4 sm:flex-row sm:items-center"><span className="grid size-10 shrink-0 place-items-center rounded-lg bg-[#E7F8F3] text-[#0D8F7B]"><BookOpenCheck size={20}/></span><div className="min-w-0 flex-1"><b className="block truncate">{item.courseTitle}</b><p className="mt-1 truncate text-sm text-[#657794]">{item.fullName||'Learner'} · {item.email}</p></div><button type="button" disabled={busy===item.entitlementId} onClick={()=>void remove(item)} className="inline-flex items-center justify-center gap-2 rounded-lg border border-red-200 px-4 py-2.5 text-sm font-bold text-red-700 hover:bg-red-50 disabled:opacity-50"><Trash2 size={16}/>{busy===item.entitlementId?'Removing...':'Remove access'}</button></article>)}{!shown.length&&<div className="rounded-lg border border-dashed p-8 text-center text-sm text-[#657794]">No active course access matches this search.</div>}</div></section>
}
