'use client';
/* oxlint-disable next/no-html-link-for-pages, jsx-a11y/control-has-associated-label */
import { useMemo, useState } from 'react';
import { Search, SlidersHorizontal } from 'lucide-react';
import { courses as defaultCourses, formatPrice, type Course } from '@/lib/course-data';

export function CourseCatalog({ courses = defaultCourses }: { courses?: Course[] }) {
  const [query, setQuery] = useState('');
  const [category, setCategory] = useState('All');
  const categories = ['All', ...new Set(courses.map((course) => course.category))];
  const results = useMemo(() => courses.filter((course) => (category === 'All' || course.category === category) && `${course.title} ${course.category} ${course.description}`.toLowerCase().includes(query.toLowerCase())), [query, category, courses]);
  return <><div className="mt-8 flex flex-col gap-3 sm:flex-row"><label className="flex flex-1 items-center gap-3 rounded-lg border bg-white px-4"><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} className="h-12 w-full outline-none" placeholder="Search courses and skills" aria-label="Search courses" /></label><label className="flex h-12 items-center gap-2 rounded-lg border bg-white px-4 font-semibold"><SlidersHorizontal size={17} /><select aria-label="Filter by category" value={category} onChange={(event) => setCategory(event.target.value)} className="bg-transparent outline-none">{categories.map((item) => <option key={item}>{item}</option>)}</select></label></div><p className="mt-6 text-sm text-[#5d696c]">{results.length} {results.length === 1 ? 'course' : 'courses'}</p><div className="mt-5 grid gap-7 sm:grid-cols-2 lg:grid-cols-3">{results.map((course, index) => <a key={course.slug} href={`/course/${course.slug}`} className="overflow-hidden rounded-xl border bg-white transition hover:-translate-y-1 hover:shadow-lg"><div className={`course-cover course-cover-${index + 1} aspect-[16/9] p-5 text-white`}><span className="text-xs">{course.category}</span><p className="mt-14 font-heading text-xl font-bold">{course.shortTitle}<span className="text-[#43D5B7]">.</span></p></div><div className="p-5"><p className="text-xs font-semibold text-[#0870C9]">{course.category} · {course.level}</p><h2 className="mt-2 font-heading text-lg font-bold leading-6">{course.title}</h2><p className="mt-3 line-clamp-2 text-sm leading-6 text-[#5d696c]">{course.description}</p><div className="mt-5 flex justify-between border-t pt-4 text-sm"><span>{course.sections.reduce((total, section) => total + section.lessons.length, 0)} lessons</span><b>{formatPrice(course)}</b></div></div></a>)}</div>{!results.length && <div className="mt-8 rounded-xl border bg-white p-10 text-center"><h2 className="font-heading text-xl font-bold">No matching courses</h2><button onClick={() => { setQuery(''); setCategory('All'); }} className="mt-5 rounded-lg border px-4 py-2 font-semibold">Clear filters</button></div>}</>;
}
