import Link from 'next/link';
import { Check, ChevronDown, Clock, FileDown, Globe2, Lock, PlayCircle } from 'lucide-react';
import { SiteHeader } from '@/components/site-header';
import { course } from '@/lib/course-data';

export const metadata={title:course.title,description:course.description};
export default function CoursePage(){return <><SiteHeader/><main>
  <section className="bg-[#073d49] text-white"><div className="mx-auto max-w-[1180px] px-5 py-12 lg:px-8"><p className="text-sm text-white/65">Courses / Development / {course.title}</p><div className="mt-6 max-w-[760px]"><p className="text-sm font-semibold text-[#62e3c3]">Development · Beginner</p><h1 className="mt-3 font-heading text-[clamp(2rem,5vw,3rem)] font-bold leading-[1.12] tracking-tight">{course.title}</h1><p className="mt-5 text-lg leading-8 text-white/80">{course.description}</p><div className="mt-6 flex flex-wrap gap-5 text-sm text-white/75"><span>Created by <b className="text-white">Claremint</b></span><span className="inline-flex items-center gap-1.5"><Globe2 size={15}/> English</span><span>Updated September 2026</span></div></div></div></section>
  <div className="mx-auto grid max-w-[1180px] gap-12 px-5 py-12 lg:grid-cols-[minmax(0,1fr)_340px] lg:px-8"><div>
    <section className="rounded-xl border bg-white p-6 md:p-8"><h2 className="font-heading text-2xl font-bold">What you’ll learn</h2><ul className="mt-6 grid gap-x-8 gap-y-4 md:grid-cols-2">{course.outcomes.map(x=><li key={x} className="flex gap-3 text-sm leading-6"><Check className="mt-0.5 shrink-0 text-[#008d7c]" size={18}/>{x}</li>)}</ul></section>
    <section className="mt-10"><h2 className="font-heading text-2xl font-bold">Course content</h2><div className="mt-2 flex flex-wrap gap-4 text-sm text-[#5d696c]"><span>5 sections</span><span>17 lessons</span><span>{course.duration}</span></div><div className="mt-5 overflow-hidden rounded-xl border bg-white">{course.sections.map((section,si)=><details key={section.title} open={si===0} className="group border-b last:border-0"><summary className="flex cursor-pointer list-none items-center gap-3 bg-[#f7f9f9] px-5 py-4 font-heading font-bold"><ChevronDown className="transition group-open:rotate-180" size={18}/>{section.title}<span className="ml-auto text-xs font-normal text-[#5d696c]">{section.lessons.length} lessons</span></summary><div>{section.lessons.map((l,i)=><div key={l[0] as string} className="flex items-center gap-3 border-t px-5 py-3.5 text-sm"><span className="w-6 text-xs text-[#7b8789]">{String(i+1).padStart(2,'0')}</span>{l[2]?<PlayCircle size={17} className="text-[#007a9f]"/>:<Lock size={15} className="text-[#9aa4a6]"/>}<span>{l[0]}</span>{l[2]&&<Link href={`/learn/${course.slug}/lesson/${l[3]}`} className="ml-auto text-xs font-semibold text-[#007a9f]">Free preview</Link>}<span className={l[2]?'hidden text-xs text-[#718083] sm:block':'ml-auto text-xs text-[#718083]'}>{l[1]}</span></div>)}</div></details>)}</div></section>
    <section className="mt-10"><h2 className="font-heading text-2xl font-bold">Requirements</h2><ul className="mt-4 list-disc space-y-2 pl-5 text-[#465457]">{course.requirements.map(x=><li key={x}>{x}</li>)}</ul></section>
  </div><aside className="lg:-mt-60"><div className="sticky top-6 overflow-hidden rounded-xl border bg-white shadow-[0_18px_50px_rgba(0,40,50,.15)]"><div className="portfolio-art grid aspect-video place-items-center text-white"><button className="grid size-14 place-items-center rounded-full bg-white text-[#005a70]" aria-label="Play preview"><PlayCircle size={30}/></button></div><div className="p-6"><p className="text-3xl font-bold">$19.00</p><Link href={`/checkout/${course.slug}`} className="mt-5 block rounded-lg bg-[#005a70] px-5 py-3.5 text-center font-semibold text-white">Buy course</Link><p className="mt-3 text-center text-xs text-[#687477]">Secure payment handled by Stripe</p><ul className="mt-6 space-y-3 text-sm"><li className="flex gap-3"><Clock size={17}/> Lifetime access</li><li className="flex gap-3"><FileDown size={17}/> 3 downloadable resources</li><li className="flex gap-3"><Check size={17}/> Completion certificate</li></ul></div></div></aside>
  </div></main></>}
